name: Setup and run Notebook
on:
  # Run on the 1st of each month from March to December (Active F1 Months)
  schedule:
    - cron: '0 0 1 3-12 *'  # At 00:00 on day-of-month 1 in March-December

  push:
    branches:
      - master 
    paths:
      - '**.ipynb'  # Trigger only when notebook files change
      - 'data/**'   # Trigger only when data files change

  # Allow manual trigger
  workflow_dispatch:

jobs:
  convert-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt

      - name: Create new datasets
        run: |
         python extend-datasets.py

      - name: Execute and convert notebooks to HTML
        run: |
            chmod +x notebook-to-html.sh
            ./notebook-to-html.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
